### ISSUE TITLE
CRC check fails

### ISSUE THREAD

**Issue by jokull** [crosspop/okydoky#6]
We’ve just set up Okydoky for our internal documentation and so far loving it. We’ve put it up in an EC2 micro instance with nginx in front reverse proxying to okydoky on port 8080. Everything was working fine until we started getting these errors:

```
Traceback (most recent call last):
  File "/web/okydoky/venv/local/lib/python2.7/site-packages/eventlet/hubs/hub.py", line 346, in fire_timers
    timer()
  File "/web/okydoky/venv/local/lib/python2.7/site-packages/eventlet/hubs/timer.py", line 56, in __call__
    cb(*args, **kw)
  File "/web/okydoky/venv/local/lib/python2.7/site-packages/eventlet/event.py", line 163, in _do_send
    waiter.switch(result)
  File "/web/okydoky/venv/local/lib/python2.7/site-packages/okydoky/app.py", line 255, in build_main
    working_dir = extract(filename, save_dir)
  File "/web/okydoky/venv/local/lib/python2.7/site-packages/okydoky/app.py", line 297, in extract
    logger.debug('tar.getnames() = %r', tar.getnames())
  File "/usr/lib/python2.7/tarfile.py", line 1813, in getnames
    return [tarinfo.name for tarinfo in self.getmembers()]
  File "/usr/lib/python2.7/tarfile.py", line 1805, in getmembers
    self._load()        # all members, we first have to
  File "/usr/lib/python2.7/tarfile.py", line 2380, in _load
    tarinfo = self.next()
  File "/usr/lib/python2.7/tarfile.py", line 2315, in next
    self.fileobj.seek(self.offset)
  File "/usr/lib/python2.7/gzip.py", line 429, in seek
    self.read(1024)
  File "/usr/lib/python2.7/gzip.py", line 256, in read
    self._read(readsize)
  File "/usr/lib/python2.7/gzip.py", line 303, in _read
    self._read_eof()
  File "/usr/lib/python2.7/gzip.py", line 342, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xd101d3da != 0xadadbec0L
```

Okydoky was managing to build the documentation just fine up until this point. Now we get these errors consistently.

Here is the NGiNX config

```
upstream okydoky {
    server localhost:8080 fail_timeout=0;
}

server {
    listen 80 default;
    client_max_body_size 4G;
    server_name _;

    keepalive_timeout 5;

    # path for static files
    root /web/okydoky/public;

    location / {
        # checks for static file, if not found proxy to app
        try_files $uri @proxy_to_app;
    }

    location @proxy_to_app {
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_redirect off;

        proxy_pass   http://okydoky;
    }

    error_page 500 502 503 504 /500.html;
    location = /500.html {
        root /web/okydoky/public;
    }
}
```

I cleared the data directory, reauthenticated and pushed again. This time it worked. I’ll report back if this happens again.

BTW Great work! Very useful tool. Might be good as a SaaS thing?

**Comment by dahlia** [comment]
Might GitHub serve a broken tarball by any chance?  I currently have no idea though.  :anguished:
